name: lecture-datascience
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.8
  - anaconda=2020.11
  - conda:
    - python-graphviz
    - fiona
    - geopandas  
    - jupyter-book>=0.11.0,<0.12.0
    - sphinxext-rediraffe
    - sphinx-multitoc-numbering
    - joblib
    - interpolation
    - pyLDAvis >= 3.3.0
    - gensim 
    - folium 
    - descartes 
    - pyarrow
    - xgboost
    - graphviz
    - scikit-learn >= 0.24.0
    - bokeh
    - sphinxcontrib-bibtex
    - nltk
    - seaborn
    - patsy
    - quandl
    - statsmodels
    - quantecon
    - openpyxl
    - plotly
    - lxml
    - pandas_datareader
    - jedi >= 0.16
  - pip
  - pip:
    - sphinx-tojupyter
    - sphinx_exercise
    - quantecon-book-theme >=0.2.5,<0.3.0      